run:
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - lll
  disable:
    - typecheck
    - contextcheck
    - protogetter
  presets:
    - bugs

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
  staticcheck:
    checks:
      - "all"
  govet:
    enable:
      - nilness
      - defers
      - lostcancel
      - bools
      - fieldalignment
      - nilfunc
      - httpresponse
      - printf
      - timeformat
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite
      - waitgroup

  gosec:
    includes:
      - G101 # Look for hard coded credentials

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - staticcheck
      text: "QF1008:"
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - lll
        - govet
    - path: .go
      linters:
        - typecheck
        - contextcheck
        - exhaustive
    - path: generator.go
      linters:
        - lll
