services:
  postgres:
    image: postgres:16
    container_name: petstore_db
    ports:
      - "65300:5432"
    volumes:
      - /tmp/fws-facade-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "petstore"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "petstore"]
      start_period: 5s
      interval: 2s
      timeout: 1s
      retries: 100

  flyway:
    pull_policy: build
    build:
      context: internal/adapters/repository/postgres/flyway
    container_name: petstore_migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://admin:admin@postgres:5432/petstore"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: petstore-otel-collector
    ports:
      - "4318:4318" # HTTP
    volumes:
      - ./local/telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger

  tempo:
    image: grafana/tempo:2.6.0
    ports:
      - "3200:3200" # tempo
      - "14317:4317" # otlp grpc
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "./local/telemetry/tempo.yaml:/etc/tempo.yaml"

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./local/telemetry/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "13000:3000"

  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    volumes:
      - ./local/telemetry/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
