services:
  postgres:
    image: postgres:16
    container_name: petstore_db
    ports:
      - "65300:5432"
    volumes:
      - /tmp/petstore-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "petstore"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "petstore"]
      start_period: 5s
      interval: 2s
      timeout: 1s
      retries: 100

  flyway:
    pull_policy: build
    build:
      context: internal/adapters/repository/postgres/flyway
    container_name: petstore_migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://admin:admin@postgres:5432/petstore"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: petstore_otel_collector
    ports:
      - "4318:4318" # HTTP
      - "4317:4317" # GRPC
    volumes:
      - ./local/telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    depends_on:
      - tempo
      - loki

  # Tempo for trace storage
  tempo:
    image: grafana/tempo:latest
    container_name: petstore_tempo_traces
    ports:
      - "3200:3200" # tempo
      - "14317:4317" # otlp grpc
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "./local/telemetry/tempo.yaml:/etc/tempo.yaml"

  # # Loki for log aggregation
  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./local/telemetry/loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo

volumes:
  tempo_data:
  loki_data:
  grafana_data:
  postgres_data:
