apiVersion: 1

datasources:
  - name: Traces
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "+1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{exporter="OTLP"} | json | traceid="$${__span.traceId}" | spanid="$${__span.spanId}" | line_format "{{.body}}"'
      lokiSearch:
        datasourceUid: loki

  - name: Logs
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceid":"([a-f0-9]+)"'
          name: Trace ID
          urlDisplayLabel: "Trace"
          url: "$${__value.raw}"

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: prometheus
