apiVersion: 1

datasources:
  - name: Traces
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo

  - name: Logs
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: loki
    # TODO: it seems like this isn't being used
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceid":"([a-f0-9]+)"'
          matherType: label
          name: Trace ID
          urlDisplayLabel: "View Trace"
          url: ${__value.raw}
