CREATE TYPE PET_STATUS AS ENUM ('AVAILABLE', 'PENDING', 'SOLD');

CREATE TABLE PETS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    STATUS PET_STATUS NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IDX_PETS_STATUS ON PETS (STATUS);
